language: cpp
sudo: required
dist: trusty

notifications:
  email: false

branches:
  only:
    - master

matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode7.3
      env: C_COMPILER=clang CXX_COMPILER=clang++ CONFIGURATION=Release

    - os: linux
      compiler: clang
      env: C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8 CONFIGURATION=Release

    - os: linux
      compiler: gcc
      env: C_COMPILER=gcc CXX_COMPILER=g++ CONFIGURATION=Release

    - os: linux
      compiler: clang
      env: C_COMPILER=clang-format-3.8 CXX_COMPILER=clang-format-3.8 CONFIGURATION=Formatting

before_install:
  - ./scripts/travis-before-install.sh $TRAVIS_OS_NAME

install:
  - git submodule update --init --recursive

script:
  - ./scripts/travis-build.sh $CONFIGURATION $C_COMPILER $CXX_COMPILER
